### ISSUE TITLE
brew install cpp-ethereum CMake Error

### ISSUE THREAD

**Issue by zachgitt** [ethereum/homebrew-ethereum#124]
I am reporting the following error as per the directions:
OS X El Capitan
Version 10.11.6

==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/zachgitt/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_
Last 15 lines from /Users/zachgitt/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/EthCompilerSettings.cmake:76 (message):
  This compiler AppleClang 8.0.0.8000042 is not able to compile required
  libff.  Install clang 4+ from Homebrew.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20170829-37713-3ouvmx/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121

**Comment by Fooneyguy** [comment]
I am having this exact error, not sure what do to about it or even where to start troubleshooting.

**Comment by leaplee** [comment]
Updating Homebrew...
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/xxx/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/EthCompilerSettings.cmake:76 (message):
  This compiler AppleClang 8.1.0.8020042 is not able to compile required
  libff.  Install clang 4+ from Homebrew.
Call Stack (most recent call first):
  CMakeLists.txt:93 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20170901-22054-dt9ojo/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121
brew install cpp-ethereum CMake Error https://github.com/ethereum/homebrew-ethereum/issues/124

**Comment by vsaraph** [comment]
I got an almost identical error message when running brew install cpp-ethereum.
I am running macOS Sierra 10.12.3. Output is as follows:

==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/vsadmin/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cell
Last 15 lines from /Users/vsadmin/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/EthCompilerSettings.cmake:68 (message):
  This compiler AppleClang 8.0.0.8000042 is not able to compile required
  libff.  Install clang 4+ from Homebrew.
Call Stack (most recent call first):
  CMakeLists.txt:94 (include)

**Comment by ftarasenko** [comment]
If you look to line 68 of cmake/EthCompilerSettings.cmake, it shows that AppleClang of version 8.4 is required. You can install new xcode (9.0 for example) and set compiler with `sudo xcode-select -s /Users/username/Downloads/Xcode-beta.app/Contents/Developer`.
Configuration of homebrew and version of clang, you're using can be checked with `brew config`.

**Comment by nicexe** [comment]
The new xcode is only available on the last OSX releases. People on 1osx 10.10 and probably 10.11 won't be able to get it.

**Comment by dwampler35** [comment]
Is the cmake compiler check confusing Xcode versions with clang versions?
clang only goes up to 8.1.0 (clang-802.0.42) on the latest MacOs

https://trac.macports.org/wiki/XcodeVersionInfo

**Comment by joeselway** [comment]
I am getting this error on 10.12.6 with Xcode 8.3.3 which is latest non-beta release.
Does this now require the Xcode 9 beta?

**Comment by gruvin** [comment]
Assuming a previous ...

```
$ brew install llvm
```
...

```
$ vi  /Homebrew/Library/Taps/ethereum/homebrew-ethereum/cpp-ethereum.rb
```

Insert a `CMAKE_CXX_COMPILER` line ...

```
    args << "-DVMTRACE=1" if build.with? "vmtrace"
    args << "-DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang"

    system "cmake", *args
    system "make"
    system "make", "install"
```

Try again ...

```
$ brew install cpp-ethereum
```

Good luck.

**Comment by hemc4** [comment]
I am seeing the same error on OSX 10.11.4

`➜  build git:(develop) gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by SleepyNab** [comment]
**Option 1:**
In the homebrew forlmula instead of the single compiler line mentioned by @gruvin insert the following
`args << "-DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++"
    args << "-DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang"
    ENV.append 'LDFLAGS', '-L/usr/local/opt/llvm/lib'
    ENV.append 'CPPFLAGS', '-I/usr/local/opt/llvm/include'
    ENV.append 'CPPFLAGS', '-Wno-error=tautological-constant-out-of-range-compare'`
the last line I needed to suppress some warnings... you can similarily append other flags

**Option 2**
This option that worked better for me... just after installing llvm
`$ brew install llvm`

set these env variables:
`export CC=/usr/local/opt/llvm/bin/clang
export CXX=/usr/local/opt/llvm/bin/clang++ 
export CXXFLAGS='-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/'
export CPPFLAGS='-I/usr/local/opt/llvm/include -I/usr/local/opt/llvm/include/c++/v1/'
export LDFLAGS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib'`

then build as mentioned in https://github.com/ethereum/cpp-ethereum

`
git clone --recursive https://github.com/ethereum/cpp-ethereum.git
cd cpp-ethereum
mkdir build; cd build  # Create a build directory.
cmake ..               # Configure the project.
cmake --build .        # Build all default targets.`

**Comment by wowpages** [comment]
SleepyNab's Option 2 seemed to be going well - High Sierra 10.13 - until `cmake -- build . ` which was doing fine up to this:

`
Scanning dependencies of target web3jsonrpc
[ 62%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/AccountHolder.cpp.o
[ 62%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/AdminEth.cpp.o
[ 63%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/AdminNet.cpp.o
[ 63%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/AdminUtils.cpp.o
[ 64%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/Debug.cpp.o
[ 64%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/Eth.cpp.o
[ 64%] Building CXX object libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/IpcServerBase.cpp.o
/Users/Steve/cpp-ethereum/libweb3jsonrpc/IpcServerBase.cpp:145:6: error: use of undeclared identifier 'OnRequest'
                                        OnRequest(r, reinterpret_cast<void*>((intptr_t)_connection));
                                        ^
1 error generated.
make[2]: *** [libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/IpcServerBase.cpp.o] Error 1
make[1]: *** [libweb3jsonrpc/CMakeFiles/web3jsonrpc.dir/all] Error 2
make: *** [all] Error 2
`

so kind of stuck now. I'm open to suggestions!

**Comment by SleepyNab** [comment]
Yes that is also solved here:
https://github.com/ethereum/cpp-ethereum/issues/4607

**Comment by tholcom2** [comment]
I had a similar error.. I was running El Capitan so I had to update my OS to Sierra to update to Xcode 9.x.x - nothing more exciting than a forced update!

Then ensure that your machine recognized the update with:
`$ sudo xcode-select -s /Applications/Xcode.app/Contents/Developer/`

With OS Sierra simply updating Xcode is not enough, you need to manually enable inline tools with
'$ xcode-select --install'

Then remove whatever existing clone you were trying to use before, and re-clone. And start from the beginning. This is important since you need to re-accept the license with your updated version of Xcode. You might not _really_ need to re-clone but if you're reading this better to just be safe.

You should then be able to (hopefully) complete the build without any further errors!

It is possible to avoid this by installing an updated version of clang with 
'brew install llvm'
but then you need to update your path and bash profile etc.. so it's probably more of a headache than it's worth unless you're really attached to your current version of Xcode.

**Comment by chfast** [comment]
The easiest way would be to upgrade XCode to the recent one. None simple fix exists on our side.

**Comment by chfast** [comment]
Can this be closed?

**Comment by axic** [comment]
> None simple fix exists on our side.

I suppose the brew file should require a minimum xcode version?
