### ISSUE TITLE
Getting issues while installing solidity

### ISSUE THREAD

**Issue by surathmu** [ethereum/homebrew-ethereum#177]
Getting following error 

```
[ 15%] Building CXX object libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o
cd /tmp/solidity-20180718-28158-1w4i8vn/solidity_0.4.24/libevmasm && /home/suh/.linuxbrew/bin/ccache /home/surath/.linuxbrew/Library/Homebrew/shims/linux/er/g++-5   -isystem /tmp/solidity-20180718-28158-1w4i8vn/solidity_0.4.24/depsclude -I/tmp/solidity-20180718-28158-1w4i8vn/solidity_0.4.24/include -I/tmp/sdity-20180718-28158-1w4i8vn/solidity_0.4.24 -isystem /home/surath/.linuxbrew/lude  -std=c++11 -fuse-ld=gold -O3 -DNDEBUG   -fstack-protector-strong -Wall xtra -Werror -Wno-unknown-pragmas -o CMakeFiles/evmasm.dir/Assembly.cpp.o -c p/solidity-20180718-28158-1w4i8vn/solidity_0.4.24/libevmasm/Assembly.cpp
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
libevmasm/CMakeFiles/evmasm.dir/build.make:65: recipe for target 'libevmasm/CeFiles/evmasm.dir/Assembly.cpp.o' failed
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 4
make[2]: Leaving directory '/tmp/solidity-20180718-28158-1w4i8vn/solidity_0.4'
CMakeFiles/Makefile2:219: recipe for target 'libevmasm/CMakeFiles/evmasm.dir/' failed
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
make[1]: Leaving directory '/tmp/solidity-20180718-28158-1w4i8vn/solidity_0.4'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues
```

**Comment by axic** [comment]
@surathmu what compiler and version of the compiler (gcc or clang) are you using?

**Comment by surathmu** [comment]
Following is the details of gcc version
==========================
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.6' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.6)

**Comment by princeriley** [comment]
New installation issue using brew .... 
brew install solidity
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and homebrew/cask-versions).
No changes to formulae.

==> Installing solidity from ethereum/ethereum
==> Installing dependencies for ethereum/ethereum/solidity: ccache and z3
==> Installing ethereum/ethereum/solidity dependency: ccache
==> Downloading https://www.samba.org/ftp/ccache/ccache-3.4.3.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ccache/3.4.3 --mandir=/usr/local/Cellar/ccache/3.4.3/share/man
==> make
==> make install
==> Caveats
To install symlinks for compilers that will automatically use
ccache, prepend this directory to your PATH:
  /usr/local/opt/ccache/libexec

If this is an upgrade and you have previously added the symlinks to
your PATH, you may need to modify it to the path specified above so
it points to the current version.

NOTE: ccache can prevent some software from compiling.
ALSO NOTE: The brew command, by design, will never use ccache.
==> Summary
🍺  /usr/local/Cellar/ccache/3.4.3: 57 files, 247.0KB, built in 17 seconds
==> Installing ethereum/ethereum/solidity dependency: z3
==> Downloading https://github.com/Z3Prover/z3/releases/download/z3-4.7.1/z3-4.7.1.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/32944298/3554a43e-5ddd-11e8-81be-469ae6c94176?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-A
######################################################################## 100.0%
==> python2.7 scripts/mk_make.py --prefix=/usr/local/Cellar/z3/4.7.1 --python --pypkgdir=/usr/local/Cellar/z3/4.7.1/lib/python2.7/site-packages --staticlib
==> make
==> make install
🍺  /usr/local/Cellar/z3/4.7.1: 103 files, 91.3MB, built in 3 minutes 43 seconds
==> Installing ethereum/ethereum/solidity
==> Downloading https://github.com/ethereum/solidity/releases/download/v0.4.25/solidity_0.4.25.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/40892817/f5685400-b797-11e8-9630-d0694d11b507?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-A
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/solidity/0.4.25 -DCMAKE_BUILD_TYPE=Release -DC
==> make install
Last 15 lines from /Users/********/Library/Logs/Homebrew/solidity/02.make:
cd /tmp/solidity-20181009-30425-11881hc/solidity_0.4.25/libevmasm && /usr/local/bin/ccache /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -I/tmp/solidity-20181009-30425-11881hc/solidity_0.4.25/include -I/tmp/solidity-20181009-30425-11881hc/solidity_0.4.25 -isystem /tmp/solidity-20181009-30425-11881hc/solidity_0.4.25/deps/include -isystem /usr/local/include  -std=c++11 -O3 -DNDEBUG   -Wimplicit-fallthrough -Wall -Wextra -Werror -Wno-unknown-pragmas -o CMakeFiles/evmasm.dir/JumpdestRemover.cpp.o -c /tmp/solidity-20181009-30425-11881hc/solidity_0.4.25/libevmasm/JumpdestRemover.cpp
/tmp/solidity-20181009-30425-11881hc/solidity_0.4.25/libevmasm/Assembly.cpp:377:30: error: chosen constructor is explicit in copy-initialization
        optimiseInternal(_settings, {});
                                    ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/set:428:14: note: constructor declared here
    explicit set(const value_compare& __comp = value_compare())
             ^
/tmp/solidity-20181009-30425-11881hc/solidity_0.4.25/libevmasm/Assembly.h:147:100: note: passing argument to parameter '_tagsReferencedFromOutside' here
        std::map<u256, u256> optimiseInternal(OptimiserSettings const& _settings, std::set<size_t> const& _tagsReferencedFromOutside);
                                                                                                          ^
1 error generated.
make[2]: *** [libevmasm/CMakeFiles/evmasm.dir/Assembly.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libevmasm/CMakeFiles/evmasm.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by yazhiwang** [comment]
Hey there, 
I always get following error when trying to install solidity on Mac, I have all updates installed. But still kept giving me this:

>>>>>>>

/usr/local/bin/ranlib libsolidity.a
[ 97%] Built target solidity
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
Getting issues while installing solidity https://github.com/ethereum/homebrew-ethereum/issues/177
Make a Error when installing Solidity https://github.com/ethereum/homebrew-ethereum/issues/178

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

**Comment by axic** [comment]
@princeriley your issue seems to be different from @surathmu's. Please open a separate ticket.

@yazhiwang your issue doesn't give much detail so hard to know what's going on.

Also please note this line from the README:
> Important note: reporting issues with any of these brews should be done at their respective repositories (Go client, C++ client and Solidity).

**Comment by axic** [comment]
@surathmu your issue seems to be running out of memory, likely you are doing it on a VM.
