### ISSUE TITLE
Homestead update - cpp-ethereum ethminer

### ISSUE THREAD

**Issue by b1uebox** [ethereum/homebrew-ethereum#61]
homebrew-ethereum needs updating to Homestead. ethminer 1.0rc2 does not submit shares after fork on 3/14/16. When can an update be expected?

**Comment by bobsummerwill** [comment]
Really?  Hmm.   Thanks for the report.

The version shown in Homebrew is wrong and has been stuck at 1.0rc2 for several months.   I discovered that recently, but that displayed version doesn't affect the content.   TODO is tracked by https://github.com/ethereum/webthree-umbrella/issues/279.

What is concerning, though, if your report on incorrect behaviour which you are reporting.

The versioning of ethminer is not directly related to the versioning of the Ethereum node which your miner attaches to.   Are you running an eth node from that same Homebrew install?   Or to geth?

Your issue is more likely related to that node than to the ethminer itself.    Please could you provide more details on that, @b1uebox?   Thanks!

**Comment by bobsummerwill** [comment]
BTW - Did you do ...

    brew update
    brew upgrade

I'm just testing locally, to see what Homebrew gives me on my own machine right now.

**Comment by b1uebox** [comment]
I should have clarified better, was in a hurry... I've done all the brew update/upgrades, I've tried re-installing from source (as you and others have painstakingly detailed elsewhere), etc. I also understand the miner "version" should have nothing to do with node version, also — I've been mining on Windows with the same version of Genoil's cuda miner (both opencl and cuda) for months and know that isn't the problem.

Unless this ethminer isn't geared to work with pools... Solo mining is practically impossible with less than a couple hundred MH with difficulty over 17T, so that's no longer an option.

Could it also be related to the Apple drivers? I'm using a pair of MSI R7 370's, added device ID into the AMD7000Controller.kext and AMDRadeonX4000.kext Info.plist's (csrutil disable), device ID 0x68111002; they are recognized and are functional with HDMI display output (just no Apple boot screen of course). These are "old" Pitcairn GPU's, single boost cable, and are the newest/cheapest/fastest models you can use without additional PSU. Since Genoil's ethminer won't compile on 10.11.3 without errors (I've tried everything there too), I can't use nvidia...

I run ethminer using the same command on OS X (10.11.3) as on Windows for OpenCL, that is:
ethminer -G -F http://<pool.address:port>/<additional_details_based_on_pool>
simple as it gets. I've tried coinotron, dwarfpool, and others to no avail. ethminer acts normally— getwork, hashing, etc. but it just never submits a solution, which makes me believe there's something else going on. 20MH/s should pop a submit at least once a minute or so; my GTX970's at 42MH/s submit solutions 2-3 times a minute.

Thanks anyway. Sorry if this causes too much trouble, it's more "geek scratches itch" for me and not wanting to run under bootcamp/Windows (if I can just find my Win7 installer key... :^O ).

**Comment by b1uebox** [comment]
So far all I can guess is 1) the homebrew miner opencl code must be terribly unoptimized, and/or 2) it's the Apple drivers, and/or 3) it's Apple's opencl 1.2 implementation. I'm guessing a combination of 1 & 2 since opencl 1.2 should be opencl 1.2 everywhere.

Comparing the Genoil fork on Windows and homebrew, both using opencl and each hashing 20MH/s, the Windows miner submits an effective rate 4-5 times higher than the Mac...

**Comment by bobsummerwill** [comment]
Likely any-and-all of the above!

Let's blame Apple.   I think that is fair.   See also http://arstechnica.com/gaming/2016/03/oculus-founder-rift-will-come-to-mac-if-apple-ever-release-a-good-computer/

**Comment by bobsummerwill** [comment]
Closed this issue because there is no issue as originally written.
There is an issue on webthree-umbrella tracking possibility of upstreaming Genoil changes.    Please also feel free to open a new issue on general Mac mining performance issues if you're going to keep chipping away at this "itch".    Thanks for all the info of your experiences!
