### ISSUE TITLE
Don't remove older versions when installing new versions

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/homebrew-ethereum#68]
I upgraded to geth 1.4.* but ended up having an issue and needed to downgrade. Unfortunately, the older version of geth got removed when I did this. I had to manually download from the buildserver in order to use the older version.

**Comment by debris** [comment]
That's how homebrew works... it's removes old version of library/application when the new one is installed. 

There are two possible solutions of this problem:
- command line argument for brew, eg `brew install ethereum --version 1.4.4` which specifies wanted version.
- separate receipts for old versions of ethereum (something similar to [homebrew-versions](https://github.com/Homebrew/homebrew-versions).

**Comment by bobsummerwill** [comment]
Yeah - it's a fundamental design "feature" of Homebrew:

https://github.com/ethereum/webthree-umbrella/issues/118

You can't get off this train.   You WILL move at the speed of the world.   Doesn't work?   Try again.   Sync-to-head.   Sync-to-head.   Sync-to-head.

**Comment by aakilfernandes** [comment]
Maybe an easier solution is seperate formula for each version? `brew install ethereum1.4.4`

**Comment by aakilfernandes** [comment]
Main goal should be to allow devs to downgrade geth. Not sure what path is easist

**Comment by bobsummerwill** [comment]
If devs need older versions, they can always build them from source.    Also, for geth, this is a really simple problem, because it is a static binary.

Homebrew is a REALLY CRAP mechanism for delivering versioned releases.   It is a rolling release manager.    It doesn't want to deliver anything other than the latest version.    That's what it does.

The best way to deliver old version geth versions on OS X is not to use Homebrew at all, but just to point to the binaries wherever they are within https://builds.ethereum.org/.

**Comment by bobsummerwill** [comment]
@karalabe Do you have a URL handy to the directory on https://builds.ethereum.org/ which contains the geth released binaries, please?

That is https://builds.ethereum.org/cpp-binaries-data/ for C++.

**Comment by bobsummerwill** [comment]
Or actually, you could just use https://github.com/ethereum/go-ethereum/releases, eh, @aakilfernandes?

ie. https://github.com/ethereum/go-ethereum/releases/download/v1.4.4/geth-OSX-20160517131155-1.4.4-94ad694.zip

**Comment by bobsummerwill** [comment]
But yeah - we shouldn't solve the issue of old geth binaries within Homebrew.   It's just files.
