### ISSUE TITLE
The blockchain datadir differ from myst

### ISSUE THREAD

**Issue by MartinDelille** [ethereum/homebrew-ethereum#74]
I have *Myst* installed using the following datadir path: `~/Library/Ethereum`
I installed *ethereum* installed from this tap, but it has a different datadir path: https://github.com/ethereum/homebrew-ethereum/blob/master/ethereum.rb#L59 (~/.ethereum)

Shouldn't it be the same?

**Comment by bobsummerwill** [comment]
No, they are intentionally different.

When you start Mist, it looks for a running EVM (Ethereum virtual machine) client on the default port.   If it finds one then it will attach to it.     That instance will stores its data wherever it stores it.    That differs by client (http://www.ethdocs.org/en/latest/ethereum-clients/choosing-a-client.html), and there is no guarantee on common data storage there.

In the absence of a running client, Mist will start up a node using copies of geth and eth embedded within the Mist package.    That uses a local data directory, so that it doesn't interfere with any local installation of geth which you may have running.

So it is intentional, because there is no "one-size-fits-all" solution here for Ethereum.    There is a protocol and multiple implementations of that protocol.
